---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tirervyq/blog.tired.energy/
    - /bin/cp /home/tirervyq/repositories/blog-tired-energy/index.html $DEPLOYPATH
    - /bin/cp -R /home/tirervyq/repositories/blog-tired-energy/assets $DEPLOYPATH
    - /bin/cp -R /home/tirervyq/repositories/blog-tired-energy/posts $DEPLOYPATH
