---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tirervyq/blog.tired.energy/
    - /bin/cp /home/tirervyq/repos/index.html $DEPLOYPATH
    - /bin/cp -R /home/tirervyq/repos/assets $DEPLOYPATH
    - /bin/cp -R /home/tirervyq/repos/posts $DEPLOYPATH
